<?php
/**
 * Created by PhpStorm.
 * User: Konstantin
 * Date: 03.11.2016
 * Time: 21:45
 */

namespace app\controllers;

use app\models\Category;
use Yii;
use app\models\TestForm;


class PostController extends AppController
{
    public $layout = 'basic';

    public function beforeAction($action)
    {
//        debug($action);
        if ($action->id == 'index') {
//            $this->enableCsfrValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex() {
        $this->view->title = 'Все статьи';
        if ( Yii::$app->request->isAjax ) {
//            debug($_POST);
//            debug(Yii::$app->request->post());
            return 'test';
        }

        $model = new TestForm();

        if( $model->load( Yii::$app->request->post()  ) ) {
            if( $model->validate() ) {
                Yii::$app->session->setFlash('success', 'Данные приняты');
//                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
        }

        return $this->render('test', compact('model'));

    }

    public function actionShow() {
//        $this->layout = 'main';
        $this->view->title = 'Одна статья';
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'ключевики...']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'описание страницы...']);

//        $cats = Category::find()->all;
//        $cats = Category::find()->orderBy(['id' => SORT_ASC])->all();
//        $cats = Category::find()->asArray()->all();
//        $cats = Category::find()->asArray()->where('parent = 691')->all();
//        $cats = Category::find()->asArray()->where(['parent' => 691])->all();
//        $cats = Category::find()->asArray()->where(['like', 'title', 'pp'])->all();
//        $cats = Category::find()->asArray()->where(['<=', 'id', 695])->all();
//        $cats = Category::find()->asArray()->where('parent = 691')->limit(2)->all();
//        $cats = Category::find()->asArray()->where('parent=691')->count();
//        $cats = Category::find()->asArray()->count();
//        $cats = Category::findOne(['parent'=> 691]);
//        $cats = Category::findAll(['parent'=> 691]);
//        $query = "SELECT * FROM categories WHERE title LIKE '%pp%'";
        $query = "SELECT * FROM categories WHERE title LIKE :search ";
        $cats = Category::findBySql($query, [':search' => '%pp%'])->all();



        return $this->render('show', compact('cats'));

    }

}