<?php
/**
 * Created by PhpStorm.
 * User: Konstantin
 * Date: 06.11.2016
 * Time: 21:41
 */

namespace app\models;

use yii\db\ActiveRecord;

class Product extends ActiveRecord
{
    public static function tableName()
    {
        return 'products'; // TODO: Change the autogenerated stub
    }


}